#!/usr/bin/env ansible-playbook
---
- name: setup an ansible development environment
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - bootstrap
    - update
    - fail2ban
    - common
    - buildtools
    - epel
    - python_pip
    - docker
    - users
    - postfix
    - vagrant
    - investigate
    - ansible
    - ansible_lint
    - molecule
    - ara
    - ruby
    - travis
    - git
    - atom
